import * as fs from 'fs';

import type { QueryInterface, Sequelize } from 'sequelize';
// this is just for the initial migration, don't do it later on
// this SQL was generated by Sequelize

// Use await sequelize.sync({ force: true }); after initDB(); to generate new sql for backup.sql file
const rawSql = fs.readFileSync(__dirname + '/backup.sql', 'utf-8');

interface SequelizeContext {
  context: {
    queryInterface: QueryInterface;
    Sequelize: Sequelize;
  };
}

module.exports = {
  async up({ context: { queryInterface } }: SequelizeContext) {
    await queryInterface.sequelize.query(rawSql, {});
  },

  async down({ context: { queryInterface } }: SequelizeContext) {
    await queryInterface.dropAllTables();
    await queryInterface.dropAllEnums();
    await queryInterface.dropAllSchemas();
  },
};
