export enum USER_ROLE_NAME {
  USER = 'user',
  GAME_DEV = 'gamedev',
  ADMIN = 'admin',
  SUPER_ADMIN = 'super_admin',
}

export enum USER_ROLE_LEVEL {
  USER = 1,
  GAME_DEV,
  ADMIN,
  SUPER_ADMIN,
}

export enum CAPABILITIES {
  MY_GAME_READ = 'MY_GAME_READ',
  MY_GAME_WRITE = 'MY_GAME_WRITE',
  MY_GAME_ACHIEVEMENT_READ = 'MY_GAME_ACHIEVEMENT_READ',
  MY_GAME_ACHIEVEMENT_WRITE = 'MY_GAME_ACHIEVEMENT_WRITE',
  MY_GAME_LEADERBOARD_READ = 'MY_GAME_LEADERBOARD_READ',
  MY_GAME_LEADERBOARD_WRITE = 'MY_GAME_LEADERBOARD_WRITE',
  GENERAL_READ = 'GENERAL_READ',
  GENERAL_WRITE = 'GENERAL_WRITE',
  USER_ROLE_WRITE = 'USER_ROLE_WRITE',
  USER_ROLE_READ = 'USER_ROLE_READ',
  CAPABILITY_READ = 'CAPABILITY_READ',
  CAPABILITY_WRITE = 'CAPABILITY_WRITE',
  THE_ARENA_READ = 'THE_ARENA_READ',
  THE_ARENA_WRITE = 'THE_ARENA_WRITE',
  THE_TOWER_READ = 'THE_TOWER_READ',
  THE_TOWER_WRITE = 'THE_TOWER_WRITE',
  WEAPONS_READ = 'WEAPONS_READ',
  WEAPONS_WRITE = 'WEAPONS_WRITE',
  ENEMY_READ = 'ENEMY_READ',
  ENEMY_WRITE = 'ENEMY_WRITE',
  ZONE_READ = 'ZONE_READ',
  ZONE_WRITE = 'ZONE_WRITE',
  ARENA_COMMAND = 'ARENA_COMMAND',
  ARENA_ACTION = 'ARENA_ACTION',
  TOWER_COMMAND = 'TOWER_COMMAND',
  TOWER_ACTION = 'TOWER_ACTION',
  TOWER_EVENT = 'TOWER_EVENT',
  GAMESHQ_COMMAND = 'GAMESHQ_COMMAND',
}
